print("hello world!")
print("what is your name")
myName =input()
print('it is good to meet you,' +myName)
print('the length of your name is:')
print(len(myName))
print('what is your age')
myage =input()
print('enter you will be' +str(int(myage)+1)+ 'in year.')